language: python
python:
  - "3.9"
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
# command to install dependencies
install:
  - poetry install
# command to run tests
script:
  - poetry run coverage run -m pytest
