version: "3.9"

services:
  db:
    image: "postgres:14"
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: my1etl
    restart: always
